name: BetterEconomy
version: ${version}
main: me.hsgamer.bettereconomy.BetterEconomy
api-version: 1.21
depend:
  - Metaverse
softdepend:
  - Vault
  - PlaceholderAPI
authors:
  - HSGamer
  - takahatashun
  - ohAlee
description: A better economy plugin for Minecraft servers.
folia-supported: true